apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resumeval
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps 
  sources:
  - repoURL: ghcr.io/ashupednekar/charts
    targetRevision: x
    chart: resumeval
    helm:
      values: |
        s3:
          endpoint: minio.essentials.svc:9000
          access_key: ashudev
          secret_key: minioadmin
  #  helm:
  #    valueFiles:
  #    - $values/values.yaml
  #- repoURL: 'git@github.com:ashupednekar/deploy'
  #  targetRevision: apps 
  #  ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
